### PR TITLE
introduce Connection.List

### PR DESCRIPTION
**Pull request by mzmousa**
This PR adds the `get connections` management API call as a Connection.List method.

More info https://auth0.com/docs/api/management/v2#!/Connections/get_connections

I haven't tested this - could you point me in the right direction on how I can fork/test with my changes locally? Thank you!

### CODE REVIEW

**Comment by alexkappa** [comment]
Thanks for this @mzmousa, you can test this by setting the `AUTH0_DOMAIN`,`AUTH0_CLIENT_ID` and `AUTH0_CLIENT_SECRET` environment variables and running `go test ./...`.

Depending on your account, you might have trouble passing the custom domain tests which require a paid account. If thats the case you can also skip those by running isolated tests:

```sh
go test ./... -run ^TestConnection$ -v
```

I should add a note to the README on building/testing locally. For some reason the wercker (CI) builds don't report back to github, so I'll need to fix that too :(

Cheers,
Alex

**Comment by mzmousa** [comment]
`cd go-auth0/auth0/internal/client`
```
$ go test ./... -run ^TestConnection$ -v
testing: warning: no tests to run
PASS
ok  	github.com/go-auth0/auth0/internal/client	0.016s [no tests to run]
```
Is this correct?

**Comment by alexkappa** [comment]
You would have to check out the code under `$GOPATH/src/gopkg.in/auth0.v1`
<http://gopkg.in/auth0.v1> or enable module support using the
`GO111MODULE=on` flag.

**Comment by mzmousa** [comment]
I still get the "no tests to run" warning. Maybe the warning shows up but the tests actually run?
```
$ cd github.com/go-auth0/auth0/internal/client
$ GO111MODULE=on go test ./... -run ^TestConnection$ -v -count=1
go: finding github.com/PuerkitoBio/rehttp v0.0.0-20180310210549-11cf6ea5d3e9
go: finding golang.org/x/oauth2 v0.0.0-20190402181905-9f3314589c9a
go: finding golang.org/x/net v0.0.0-20190108225652-1e06a53dbb7e
go: finding golang.org/x/sync v0.0.0-20181221193216-37e7f081c4d4
go: finding google.golang.org/appengine v1.4.0
go: finding cloud.google.com/go v0.34.0
go: finding golang.org/x/net v0.0.0-20180724234803-3673e40ba225
go: finding github.com/golang/protobuf v1.2.0
go: finding golang.org/x/text v0.3.0
go: downloading github.com/PuerkitoBio/rehttp v0.0.0-20180310210549-11cf6ea5d3e9
go: downloading golang.org/x/oauth2 v0.0.0-20190402181905-9f3314589c9a
go: downloading golang.org/x/net v0.0.0-20190108225652-1e06a53dbb7e
# crypto/x509
ld: warning: text-based stub file /System/Library/Frameworks//CoreFoundation.framework/CoreFoundation.tbd and library file /System/Library/Frameworks//CoreFoundation.framework/CoreFoundation are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks//Security.framework/Security.tbd and library file /System/Library/Frameworks//Security.framework/Security are out of sync. Falling back to library file for linking.
testing: warning: no tests to run
PASS
ok  	gopkg.in/auth0.v1/internal/client	0.023s
```
I'll also try doing the first option you mentioned.

**Comment by mzmousa** [comment]
Ok I'm making progress. Looks like I shouldn't be `cd`'ing into `internal/client`:
```
$ cd $GOPATH/src/github.com/go-auth0/auth0
$ GO111MODULE=on go test ./... -run ^TestConnection$ -v
```

**Comment by mzmousa** [comment]
Looks like I was able to add and pass the tests. 

Some of the output I saw:
```
$ cd $GOPATH/src/github.com/go-auth0/auth0
$ GO111MODULE=on go test ./... -run ^TestConnection$ -v
PASS
ok  	gopkg.in/auth0.v1	              [no tests to run]
testing: warning: no tests to run
PASS
ok  	gopkg.in/auth0.v1/internal/client	          [no tests to run]
=== RUN   TestConnection
=== RUN   TestConnection/Create
2019/04/16 16:39:09 POST /api/v2/connections HTTP/1.1
Host: TRUNCATED
Content-Type: application/json
User-Agent: Go-Auth0-SDK/v1
...
    --- PASS: TestConnection/List (0.05s)
...
    --- PASS: TestConnection/Delete (0.07s)
PASS
ok  	gopkg.in/auth0.v1/management	1.079s
```

**Comment by mzmousa** [comment]
Is there anything I can do to help get this reviewed and merged? I'm using it for a work project

**Pull request merged**
