### PR TITLE
Add more MFA supports (for v5)

### PR DESCRIPTION
**Pull request by lambdalisue**
First of all, thanks for the great library :tada:

I needed to manipulate MFA things through the management APIs thus I've added some endpoints.

There is a PR for that (https://github.com/go-auth0/auth0/pull/110) but it seems staled so I've created a new one with some improvements so please check it (to be honest, I didn't notice that PR when I was writing code. I just noticed that when I tried to make a PR.)

Let me know If I should apply changes to that PR or need more extra works.

### CODE REVIEW

**Comment by lambdalisue** [comment]
I've noticed that `management.Request` or `management.URI` is public in v5 so I'll remove `m.User.Authenticators` which is undocumented yet.

**Comment by kpurdon** [comment]
@alexkappa @lambdalisue came here looking for this! Anything I can do to help move this along please let me know 👍🏻

**Comment by lambdalisue** [comment]
@alexkappa I'm sorry to rush you but please let me know what I should do to get this PR merged.

**Comment by kpurdon** [comment]
@alexkappa @paddycarey what can we do to get things like this reviewed and merged in a reasonable timeframe? I'm willing to offer my time and efforts to help in any way possible.

**Comment by lambdalisue** [comment]
While #13 is closed, this PR is no more duplicated. Could anyone remove the `duplicate` tag?

**Comment by kpurdon** [comment]
@alexkappa please assign for review. Thanks.

**Comment by kpurdon** [comment]
@yvovandoorn here is a useful PR that could use review. Thanks!

**Comment by yvovandoorn** [comment]
This looks good to merge.

**Comment by lambdalisue** [comment]
Thanks a lot 🎉

**Pull request merged**
