### PR TITLE
Added options to integrate with Twilio

### PR DESCRIPTION
**Pull request by mario-areias**
There are a few non-documented options to integrate with Twilio. This PR is to add those options on the SDK and eventually add them to the terraform provider as well.

More info https://community.auth0.com/t/using-management-api-to-create-a-twilio-connection/23576/3

### CODE REVIEW

**Comment by agoldenduck** [comment]
Hi @alexkappa is there anything we can do to get this merged? We're quite keen to use the auth0 terraform provider but need this feature in it to be able to achieve all our needs.

**Comment by alexkappa** [comment]
Yes, my apologies. I will review and get back to you soon. Thanks!

**Comment by mario-areias** [comment]
@alexkappa Thank you for merging that! Would you be so kind to release that for us?  So we can update our PR in the **terraform-provider-auth0** repository.  

Cheers,

**Comment by alexkappa** [comment]
@mario-areias unfortunately I’m away from my computer this week, so I can’t tag a new release 🙁

**Comment by mario-areias** [comment]
@alexkappa that's alright, mate. Enjoy your break. Let me know when you manage to tag a new release, yeah?

Thanks!

**Comment by alexkappa** [comment]
I managed to push v1.2.1 through the working copy app (which is pretty cool btw :)

Cheers!
Alex

**Comment by mario-areias** [comment]
@alexkappa you are such a legend! Thanks a lot!

**Pull request merged**
