### PR TITLE
http.Client wrapper shouldn't overwrite OAuth Transports if already set

### PR DESCRIPTION
**Pull request by vince-makelog**
### Proposed Changes

* Change 1
* Change 2

Fixes #0000

#### Acceptance Test Output

```
$ go test ./... -v -run TestUser

...
```

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" comments, they generate extra noise for pull request followers and do not help prioritize the request

### CODE REVIEW

**Comment by vince-makelog** [comment]
@alexkappa Do you have some time to review?

**Comment by alexkappa** [comment]
Hi @vince-makelog, could you describe the use case for this? Is there any reason you can't pass your token source as an argument to Wrap()?

**Comment by vince-makelog** [comment]
@alexkappa Hi there! Do you have some time to review the above?

**Comment by alexkappa** [comment]
Hi @vince-makelog, if I understand correctly the client already renews the token. It does not rely on long-lived tokens.

The `management.WithClientCredentials` option will use the `clientcredentials.Config` from oauth2 and do exactly as you want.

```go
api, err := management.New(domain, management.WithClientCredentials(id, secret))
if err != nil {
    // handle err
}
```

```go
// internal/client/client.go

func ClientCredentials(ctx context.Context, uri, clientID, clientSecret string) oauth2.TokenSource {
	return (&clientcredentials.Config{
		ClientID:     clientID,
		ClientSecret: clientSecret,
		TokenURL:     uri + "/oauth/token",
		EndpointParams: url.Values{
			"audience": {uri + "/api/v2/"},
		},
	}).TokenSource(ctx)
}
```

**Comment by vince-makelog** [comment]
That works thanks!

**Pull request closed without merging**
