### PR TITLE
Adds set_user_root_attributes to more connections

### PR DESCRIPTION
**Pull request by epintos**
### Proposed Changes

* Adds set_user_root_attributes to other connections

#### Acceptance Test Output

```
$ go test ./... -v -run TestUser

...
```

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" comments, they generate extra noise for pull request followers and do not help prioritize the request

### CODE REVIEW

**Comment by paddycarey** [comment]
Thanks @epintos, looks good! Seems like this is missing the generated accessors for the new fields, you'll need to run `go generate ./...` to create them.

There's an open PR in-flight which should hopefully catch this issue for new PRs in future #189

**Comment by epintos** [comment]
> Thanks @epintos, looks good! Seems like this is missing the generated accessors for the new fields, you'll need to run `go generate ./...` to create them.
> 
> There's an open PR in-flight which should hopefully catch this issue for new PRs in future #189

Hi @paddycarey. Thanks for your quick review. I've tried running:
```go
go generate ./management/connection.go
```

but nothing happens. Is that the right command?

**Comment by paddycarey** [comment]
The generate command is at the top of `management.go`, so `go generate ./management/management.go` should work. It'll be noisy though, at least until we clean up the existing accessors that weren't generated previously.

**Comment by epintos** [comment]
> The generate command is at the top of `management.go`, so `go generate ./management/management.go` should work. It'll be noisy though, at least until we clean up the existing accessors that weren't generated previously.

Ah thanks for explaining. Let me know if it looks good now :)

**Review by paddycarey — APPROVED** [review]
LGTM, but we'll need @alexkappa to hit the merge button for us. Thanks for the contribution!

**Review by alexkappa — APPROVED** [review]

**Pull request merged**
