### PR TITLE
add prompt custom text

### PR DESCRIPTION
**Pull request by gagalago**
allow customization of texts in the universal login
https://auth0.com/docs/universal-login/new-experience/text-customization-new-universal-login

### CODE REVIEW

**Comment by yvovandoorn** [comment]
Hey @gagalago, thank you for your contribution. This looks good to merge but do you mind resolving the conflicts that have been since introduced. 

Thanks!

**Comment by kiranms-newpage** [comment]
@gagalago can you please resolve the conflicts as @yvovandoorn has requested?
I am also waiting for this functionality in the terraform provider. Once it is implemented here, we can start coding in https://github.com/alexkappa/terraform-provider-auth0

**Comment by gagalago** [comment]
> @yvovandoorn , since we needed this feature, I have copied @gagalago 's code, resolved the conflicts and created a new pr at #229. Can you please review that?

thanks @kiranms-newpage , to have done this. It was not my focus anymore, so I forgot to do it.

**Comment by kiranms-newpage** [comment]
@gagalago may I know why you closed this PR? I was hoping that it will be merged ....

**Pull request closed without merging**
