### PR TITLE
add support for managing log-streams

### LINKED ISSUE #145: Add support for management of log-streams
It would be great to be able to manage log-streams through the go client. This could enable the terraform provider the ability to manage this as well. 
Blocks: https://github.com/alexkappa/terraform-provider-auth0/issues/264

### PR DESCRIPTION
**Pull request by mcalster**
This fixes #145 and #128

### CODE REVIEW

**Comment by mcalster** [comment]
go test ./management -run ^TestLogStream$
ok      gopkg.in/auth0.v4/management    1.338s

go test ./management -run ^TestSinks$
ok      gopkg.in/auth0.v4/management    8.423s

**Comment by mcalster** [comment]
@alexkappa I think this is good to go

**Comment by mcalster** [comment]
@alexkappa  I've streamlined the naming of the types introduced in this PR.
Please review. 
Test should be good, I've uncommented the Azure EventGrid test, since this requires an actual Subscription with the EventGrid resource provider activated. I've tested it on a trial subscription.

**Comment by alexkappa** [comment]
Hi @mcalster will be reviewing this today and hopefully merge it in. Thank you for submitting this work!

**Comment by alexkappa** [comment]
I did some modifications as v5 introduced a few changes, renamed types and merged. Thanks again @mcalster !

**Pull request merged**
